# Generated by Django 5.2.14 on 2026-07-01 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_address_id_alter_book_id_alter_bookimage_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='genre',
            field=models.CharField(default='General', max_length=100),
        ),
    ]
